[pytest]
markers = 

    # Mark para teste 

    usuario: Mark para todos os testes relacionados a usuario

    criaçao_usuario: Mark para todos os testes de criaçao de usuario

    criaçao_usuario_valido: Mark para os testes de criaçao de usuario com sucesso

    criaçao_usuario_duplciado: Mark para os testes de criaçao de usuario duplicado

    login: Mark para todos os testes de login existente

    login_valido: Mark para todos os testes de login valido

    login_invalido: Mark para todos os testes de login invalido

    login_senha_invalida:  Mark para todos os testes com senha do usuario invalida

    login_usuario_invalido:  Mark para todos os testes com usuario invalido

    produtos: Mark para todos os testes relacionados a produtos

    exclusao_de_produto: Mark para todos os testes de exclusao de produto

    compra_realizada_com_sucesso: Mark para todos os testes de compra realizada com sucesso


 